Repository micronaut-projects/micronaut-nats, pull requests merged in 2023-01, with the labels that each got.

#281 Fix dynamic headers isolation
  docs-examples/example-groovy/src/test/groovy/io/micronaut/nats/docs/headers/HeadersSpec.groovy
  docs-examples/example-java/src/test/java/io/micronaut/nats/docs/headers/HeadersSpec.java
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/nats/docs/headers/HeadersSpec.kt
  nats/src/main/java/io/micronaut/nats/intercept/AbstractIntroductionAdvice.java
  nats/src/main/java/io/micronaut/nats/intercept/StaticPublisherState.java
  nats/src/test/groovy/io/micronaut/nats/annotation/HeaderSpec.groovy
  src/main/docs/guide/producer/producerMethods/producerParameters/producerHeaders.adoc
Labels: type: bug, status: next major version

#275 [nats] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#284 [nats] Update common files for branch master
  .github/workflows/graalvm.yml
Labels: relates-to: build

#283 KeyValue Support
  docs-examples/example-groovy/src/test/groovy/io/micronaut/nats/AbstractNatsTest.groovy
  docs-examples/example-groovy/src/test/groovy/io/micronaut/nats/docs/jetstream/kv/KeyValueSpec.groovy
  docs-examples/example-groovy/src/test/groovy/io/micronaut/nats/docs/jetstream/kv/KeyValueStoreHolder.groovy
  docs-examples/example-java/src/test/java/io/micronaut/nats/AbstractNatsTest.java
  docs-examples/example-java/src/test/java/io/micronaut/nats/docs/jetstream/kv/KeyValueStoreHolder.java
  docs-examples/example-java/src/test/java/io/micronaut/nats/docs/jetstream/kv/KeyValueTest.java
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/nats/AbstractNatsTest.kt
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/nats/docs/jetstream/kv/KeyValueSpec.kt
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/nats/docs/jetstream/kv/KeyValueStoreHolder.kt
  nats/src/main/java/io/micronaut/nats/connect/NatsConnectionFactoryConfig.java
  nats/src/main/java/io/micronaut/nats/intercept/AbstractIntroductionAdvice.java
  nats/src/main/java/io/micronaut/nats/intercept/NatsIntroductionAdvice.java
  nats/src/main/java/io/micronaut/nats/jetstream/KeyValueFactory.java
  nats/src/main/java/io/micronaut/nats/jetstream/annotation/KeyValueStore.java
  nats/src/main/java/io/micronaut/nats/jetstream/intercept/JetStreamIntroductionAdvice.java
  nats/src/test/groovy/io/micronaut/nats/jetstream/AbstractJetstreamTest.groovy
  nats/src/test/groovy/io/micronaut/nats/jetstream/KeyValueSpec.groovy
  src/main/docs/guide/config.adoc
  src/main/docs/guide/health.adoc
  src/main/docs/guide/jetstream/keyvalue.adoc
  src/main/docs/guide/jetstream/keyvalue/kv_configuration.adoc
  src/main/docs/guide/jetstream/keyvalue/usage.adoc
  src/main/docs/guide/jetstream/streams/configuration.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#285 [nats] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build
